import Button from "components/kit/Button";
import Checkbox from "components/kit/Checkbox";
import Typography from "components/kit/Typography";
import Head from "next/head";
import styles from 'styles/test.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.root}>Hello world</main>
      <Button type="primary" size='small'>Button</Button>
      <Checkbox />
      <Typography>first</Typography>
      <Typography.Text code={true}>second</Typography.Text>
    </>
  );
}
