import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.scss";
import previewImage from "images/Designer.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.preview}>
        <div className={styles.leftSide}>
          <div className={styles.tag}>
            InCourse - образовательная платформа
          </div>
          <div className={styles.additionalText}>
            <span className={styles.marked}>Курсы маркетига</span>
            <br />
            <span>в социальных сетях</span>
          </div>
        </div>
        <div className={styles.rightSide}>
          <div className={styles.image}>
            <Image alt="" src={previewImage} fill />
          </div>
        </div>
      </section>
    </>
  );
}
