import Button from "components/kit/Button";
import Head from "next/head";
import styles from "./index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.preview}>
        <h2>InCourse - образовательная платформа</h2>
        <h1>Проверенные курсы от экспертов</h1>
        <Button type="primary" size="large">Попробовать бесплатно</Button>
      </section>
    </>
  );
}
